### ISSUE TITLE
Semantic UI Followup

### ISSUE THREAD

**Issue by outloudvi** [SchOJ/site#3]
* [x] Remake the front-end to make it whiter

Other features:
* [ ] Preserve code in edit after reloading
* [x] Slightly have a check about Social Auth

Suggestions are welcomed.

**Comment by outloudvi** [comment]
Projects are listed in [/projects/1](https://github.com/SchOJ/site/projects/1).

**Comment by outloudvi** [comment]
@SchrodingerZhu Due to the complex merge from upstream, currently I'm developing at branch `semantic_dev`.

**Comment by SchrodingerZhu** [comment]
UI for contest module and other details should be finished soon, right?

**Comment by outloudvi** [comment]
[ ] 2FA Page Redesign
